### ISSUE TITLE
ModuleNotFoundError: No module named 'win32con'

### ISSUE THREAD

**Issue by bbejot** [btsdev/global_hotkeys#4]
Did a fresh install of global hotkeys (on Windows 10) and got this error:
```
[my path]>python --version
Python 3.10.4

[my path]>pip --version
pip 22.1 from [python path]\lib\site-packages\pip (python 3.10)

[my path]>pip install global-hotkeys
Collecting global-hotkeys
  Using cached global_hotkeys-0.0.4.tar.gz (6.7 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for global-hotkeys, since package 'wheel' is not installed.
Installing collected packages: global-hotkeys
  Running setup.py install for global-hotkeys ... done
Successfully installed global-hotkeys-0.0.4

[my path]>python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from global_hotkeys import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[python path]\lib\site-packages\global_hotkeys\__init__.py", line 1, in <module>
    from .hotkey_checker import hotkey_checker
  File "[python path]\lib\site-packages\global_hotkeys\hotkey_checker.py", line 6, in <module>
    import win32con
ModuleNotFoundError: No module named 'win32con'
```
Afterwards, I pip installed `pywin32`, which contains the `win32con` module.  I'm guessing `pywin32` just needs to be added to the `requirements.txt`.

**Comment by btsdev** [comment]
Thanks for noting this. I've added pywin32 as a dependency.
